server:
  port: 8085
spring:
  application:
    name: poetry-forum
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pf_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  # Elasticsearch 配置
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: root
      password: 123456
  jackson:
    # JSON处理时忽略非空字段
    default-property-inclusion: non_null
canal:
  server:
    host: localhost
    port: 11111
  destination: example
mybatis-plus:
  type-aliases-package: com.poetryforum.entity # 别名扫描包
logging:
  level:
    com.poetryforum: debug